#!/usr/bin/env bash
# Creates .env with fresh random secrets (once) and renders the Keycloak realm from its template.
set -euo pipefail
cd "$(dirname "$0")/.."

command -v docker >/dev/null 2>&1 || { echo "Docker is required: https://docs.docker.com/get-docker/" >&2; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "Docker Compose v2 is required (docker compose ...)" >&2; exit 1; }
docker info >/dev/null 2>&1 || { echo "The Docker daemon is not reachable. Start Docker and retry." >&2; exit 1; }

secret() { openssl rand -hex 24; }

if [ ! -f .env ]; then
  umask 077
  cat > .env <<ENV
# Generated by scripts/bootstrap.sh. Local secrets only; never commit this file.
PQT_PUBLIC_URL=http://localhost:8080
PQT_BIND_ADDR=127.0.0.1
PQT_UID=$(id -u)
PQT_GID=$(id -g)
POSTGRES_PASSWORD=$(secret)
PQT_DB_MIGRATOR_PASSWORD=$(secret)
PQT_DB_APP_PASSWORD=$(secret)
PQT_DB_READ_PASSWORD=$(secret)
PQT_KAFKA_ADMIN_PASSWORD=$(secret)
PQT_KAFKA_EVENTCORE_PASSWORD=$(secret)
PQT_KAFKA_RULES_PASSWORD=$(secret)
PQT_KAFKA_SIM_PASSWORD=$(secret)
KC_ADMIN_PASSWORD=$(secret)
PQT_OIDC_CLIENT_SECRET=$(secret)
PQT_SIM_CLIENT_SECRET=$(secret)
PQT_EDGE_CLIENT_SECRET=$(secret)
PQT_VIEWER_PASSWORD=$(secret)
PQT_OPERATOR_PASSWORD=$(secret)
PQT_REVIEWER_PASSWORD=$(secret)
PQT_ADMIN_PASSWORD=$(secret)
GRAFANA_ADMIN_PASSWORD=$(secret)
ENV
  if grep -qE "^[A-Z_]+=$" .env; then echo "empty secret in .env" >&2; rm .env; exit 1; fi
  echo "created .env with fresh secrets"
fi

set -a
# shellcheck disable=SC1091
. ./.env
set +a

# Keycloak realm sslRequired: external (default, localhost mode) | none (Codespaces URL mode) | all
PQT_KC_SSL_REQUIRED="${PQT_KC_SSL_REQUIRED:-external}"
case "$PQT_KC_SSL_REQUIRED" in
  external|none|all) ;;
  *) echo "PQT_KC_SSL_REQUIRED must be external, none or all (got: $PQT_KC_SSL_REQUIRED)" >&2; exit 1 ;;
esac

mkdir -p deploy/keycloak/generated .work/reports
sed -e "s#__PUBLIC_URL__#${PQT_PUBLIC_URL}#g" \
    -e "s#__KC_SSL_REQUIRED__#${PQT_KC_SSL_REQUIRED}#g" \
    -e "s#__OIDC_CLIENT_SECRET__#${PQT_OIDC_CLIENT_SECRET}#g" \
    -e "s#__SIM_CLIENT_SECRET__#${PQT_SIM_CLIENT_SECRET}#g" \
    -e "s#__EDGE_CLIENT_SECRET__#${PQT_EDGE_CLIENT_SECRET}#g" \
    -e "s#__VIEWER_PASSWORD__#${PQT_VIEWER_PASSWORD}#g" \
    -e "s#__OPERATOR_PASSWORD__#${PQT_OPERATOR_PASSWORD}#g" \
    -e "s#__REVIEWER_PASSWORD__#${PQT_REVIEWER_PASSWORD}#g" \
    -e "s#__ADMIN_PASSWORD__#${PQT_ADMIN_PASSWORD}#g" \
    deploy/keycloak/pqt-realm.json.tmpl > deploy/keycloak/generated/pqt-realm.json
if grep -qE '__[A-Z_]+__' deploy/keycloak/generated/pqt-realm.json; then
  echo "unrendered placeholder in deploy/keycloak/generated/pqt-realm.json" >&2; exit 1
fi
chmod 644 deploy/keycloak/generated/pqt-realm.json   # read by the keycloak container user

if [ -n "${CODESPACES:-}" ] && [ "${PQT_PUBLIC_URL}" = "http://localhost:8080" ]; then
  echo "note: in GitHub Codespaces, open the console through port forwarding to localhost:8080"
  echo "      (VS Code desktop, or 'gh codespace ports forward 8080:8080' on your machine)."
fi
